Gemfile.lock
app/controllers/stages_controller.rb
app/views/stages/show.html.erb
config/routes.rb

* Adds a 'clone' button to the stage details page
* Adds a '/stages/:stage_id/clone' POST route
* Stage model is duplicated
* Owner of clone is the user who requested the clone
* Name of clone is appended with '(clone)'

Issue #16: Stage cloning functionality

---

config/puma.rb

Original code used wrong call to test effectively

Fix key check

---

app/models/avatar.rb
app/models/medium.rb
app/models/stage.rb

* stage_media is now addressable as @stage.media
* avatar_stages in now addressable as @stage.avatars
* The other side of these associations is also adjusted for sanity

Issue #29: Add sane collection addressing

---

app/controllers/stages_controller.rb
app/views/stages/_clone_stage.erb
app/views/stages/show.html.erb

This fixes the missing associations from #16 
Also gives more cloning control to the user

Amend Issue 16

---

app/controllers/stages_controller.rb

This line was not meant to make it into the repo

Remove Unneeded debugger call

---

app/models/medium.rb
app/models/stage.rb

* When user deletes Media, all StageMedium instances are removed
* When user deletes Stage, all StageMedium instances are removed

Issue #42: Add cascading deletion

---

Gemfile
app/views/messages/_message.html.erb

Auto_link reads messages and creates hyperlinks for all links

Adds/implements Auto_link gem

---

README.md

Rails Dependency Revision

---

app/views/messages/_message.html.erb

Links hyperlinked for users shouting and audience chat

Links for shout and audience

---

app/controllers/tags_controller.rb
app/models/medium.rb
app/models/medium_tag.rb
app/models/tag.rb
app/views/media/_tags.html.erb
app/views/media/show.html.erb
app/views/tags/_form.html.erb
app/views/tags/index.html.erb
app/views/tags/new.html.erb
config/routes.rb
db/migrate/20170503191720_create_medium_tags.rb
db/schema.rb
test/fixtures/medium_tags.yml
test/models/medium_tag_test.rb

Gives users the ability to add/remove tags from Medium records:

Issue #61: Medium Tagging

---

db/migrate/20170504174932_fix_media_id_type.rb
db/schema.rb

* When changing columns, up/down vs. change are better
* Need to adjust ALL references to media.id

Issue #61: Logic Adjustment for media.id

---

db/migrate/20160909173742_create_media.rb

Changing type of media.owner_id which was missed as part of #69

Amend Media Owner

---

db/migrate/20160911010848_create_stages.rb

* Changes stages.owner_id to bigint
Missed in #69

Amend Column Type of stages.owner_id

---

app/controllers/avatars_controller.rb
app/controllers/tags_controller.rb
app/models/avatar.rb
app/models/avatar_tag.rb
app/models/tag.rb
app/views/avatars/_tags.html.erb
app/views/avatars/show.html.erb
config/routes.rb
db/migrate/20170504195111_create_avatar_tags.rb
db/schema.rb
test/fixtures/avatar_tags.yml
test/models/avatar_tag_test.rb

* Leverages existing tag assignment infrastructure
* Allows users to assign tags to avatars just as with media
Also fixes a couple of referential issues

Issue #63: Avatar Tag Assignment

---

db/migrate/20170504203008_create_stage_tags.rb

And this... I why we shouldn't copy and paste

Issue #62: Fix Copy-Paste Error

---

app/controllers/avatars_controller.rb
app/models/avatar.rb
app/views/avatars/_form.html.erb

* User must now upload an image file when they create an Avatar
* User can also replace the Medium image file when they update an Avatar

Issue #85: Modify Medium along with Avatar

---

app/controllers/tags_controller.rb

Forgot to remove this line from working on #87

Remove debug statements

---

app/assets/javascripts/sounds.coffee
app/assets/stylesheets/sounds.scss
app/controllers/sounds_controller.rb
app/helpers/sounds_helper.rb
app/models/sound.rb
app/views/layouts/application.html.erb
app/views/sounds/_form.html.erb
app/views/sounds/edit.html.erb
app/views/sounds/index.html.erb
app/views/sounds/new.html.erb
app/views/sounds/show.html.erb
config/routes.rb
db/migrate/20170505190819_create_sounds.rb
db/schema.rb
test/controllers/sounds_controller_test.rb
test/fixtures/sounds.yml
test/models/sound_test.rb

* Sound resource
* CRUD actions
* Built on top of Medium resources

Issue #90: Sound Resource

---

app/controllers/tags_controller.rb
app/models/sound.rb
app/models/sound_tag.rb
app/models/tag.rb
app/views/sounds/_form.html.erb
app/views/sounds/_tags.html.erb
app/views/sounds/show.html.erb
config/routes.rb
db/migrate/20170505195702_create_sound_tags.rb
db/schema.rb
test/fixtures/sound_tags.yml
test/models/sound_tag_test.rb

Adds the ability for users to use the existing tagging system with Sound resources

Issues #93

---

app/controllers/sounds_controller.rb
app/models/sound.rb
app/views/avatars/_form.html.erb
app/views/sounds/_form.html.erb
app/views/sounds/show.html.erb
db/migrate/20170506133057_move_sounds_to_paperclip.rb
db/schema.rb

* Adds the attachment type :source to Sound
* Removes the association with Medium from Sound
* Enforces audio format uploads

Issue #98: Move Sounds to Paperclip

---

app/views/avatars/index.html.erb

* Creates thunbnail panels for each avatar
* Panels contain edit/delete buttons
* Panel distribution is responsive

Issue #102: Make Avatar Index Panel-Based

---

app/views/avatars/_panel.html.erb
app/views/avatars/_table.html.erb
app/views/avatars/_tags.html.erb
app/views/avatars/index.html.erb
app/views/sounds/_tags.html.erb
app/views/stages/_tags.html.erb
app/views/tags/_tag.html.erb

Adds the ability for users to switch the Avatar index between a panel-based and a table-based layout

Issue #104

---

app/views/avatars/edit.html.erb
app/views/sounds/edit.html.erb
app/views/stages/edit.html.erb

Adds the ability for users to manage resource tags from their respective edit pages

Issues #93, #62 and #63

---

app/views/stages/edit.html.erb

Caused by yet another copy-paste mistake.

Issue #112: Fix 500 on Stage Edit Page

---

app/assets/javascripts/channels/theatre.coffee
app/assets/stylesheets/theatre.scss
app/channels/chat_channel.rb
app/controllers/messages_controller.rb
app/views/messages/_message.html.erb
app/views/theatre/performance.html.erb

* Simplifies templates
* Performs simple match on first character of message content to see if should shout
* Strips message modifier

Issue #106: Re-align Shout Functionality

---

app/assets/javascripts/theatre.coffee
app/models/message.rb
app/views/messages/_message.html.erb
app/views/theatre/performance.html.erb

Modifiers can now be added by:
- Adding an entry to Message::Modifiers
- Adding a convience 'is_*?' method to Message
- Adding a CSS rule for the modifier

Issues #123: Chat Modifier Framework

---

app/assets/stylesheets/theatre.scss
app/models/message.rb
app/views/messages/_message.html.erb

* Adds the modifier :thought => ':'
* Adds relevant CSS rules

Issue #122: Add Thought Chat Modifier

---

app/models/message.rb

- Modifiers can now be any length
- Convenience methods are now generated.

Enhance Chat Modifier Framework

---

app/assets/stylesheets/theatre.scss
app/views/messages/_message.html.erb

* Moves chat log into speech bubbles
* Talking players are green from the right
* Talking audience members are grey from the left
* Shouting players are red from the right
* Thinking players are blue from the right

Issue #127: Themed chat bubbles

---

app/assets/javascripts/media.coffee
app/assets/stylesheets/media.scss
app/controllers/media_controller.rb
app/helpers/media_helper.rb
app/views/layouts/application.html.erb
app/views/media/_panel.html.erb
app/views/media/_table.html.erb
app/views/media/index.html.erb
config/routes.rb
test/controllers/media_controller_test.rb

* Reused Avatar index
* Navbar entry created in place of separate Avatar/Sound ones

Issue #109: Create Generalized Media Index

---

app/assets/stylesheets/theatre.scss

* Understates message differentiation to conserve space and not draw attention
* Inverses left/right between player/audience

Issue #131: Action Feedback from #127

---

app/views/avatars/_panel.html.erb
app/views/avatars/_table.html.erb
app/views/avatars/edit.html.erb
app/views/media/_panel.html.erb
app/views/media/_table.html.erb
app/views/sounds/edit.html.erb

Remove buttons that refer to deleting records now use a trashcan icon

Issue #117: Amend Record Deletion

---

app/assets/javascripts/application.js
app/views/media/index.html.erb

Media index now displays table on monitors and panels on mobile devices

Issue #118: Change Default Layout

---

app/controllers/media_controller.rb

This *should* fix the confusion in the UI (or at least, it has in my testing)

Issue #137

---

app/assets/javascripts/channels/theatre.coffee
app/assets/javascripts/theatre.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/theatre.scss
app/views/theatre/foyer.html.erb
app/views/theatre/performance.html.erb

Fixes foyer layout transitions:
Fixes navigation toggle:
Fixes chat input:
Also of note:
- Chat modifier radio buttons enable the modifier indefinitely
- Using the modifier shortcuts enables the modifier for one message
- Hovering over modifier buttons shows the shortcuts

Issue #146

---

app/views/stages/_assign_avatars.html.erb

Reverts upstage-org/limelight#150

Revert "Remove duplicate avatar assignment"

---

app/views/stages/_assign_avatars.html.erb

Byebug doesn't get installed in production so this causes an issue

Forgot Debugging Code

---

app/assets/javascripts/channels/theatre.coffee
app/assets/stylesheets/theatre.scss
app/views/theatre/performance.html.erb

Uses display: flex; rather than a bunch of col-*-* type classes

Issue #160: Replace Bootstrap layout with Flexbox

---

app/assets/stylesheets/theatre.scss

I forgot to add the overflow handling back in when I took out some unnecessary divs

Forgot Overflow

---

app/assets/stylesheets/theatre.scss
app/views/messages/_message.html.erb

Redefines the padding around each message and also tries to space them out in a clearer manner

Issues #163: Fix Message Padding

---

app/assets/stylesheets/theatre.scss

Issue #163: Halve Message Space

---

app/assets/stylesheets/theatre.scss
app/views/theatre/performance.html.erb

Adds buttons with avatar images for each avatar applied to the
stage. Resize Buttons to fit panel size. Resize images to fit button
size

Issue#144_

---

app/views/theatre/performance.html.erb

Add mouseover names for avatars

Mouseover names for avatars

---

app/assets/javascripts/channels/theatre.coffee

These two lines were accidentally removed

Reinstate two calls

---

app/assets/javascripts/cable.js
app/assets/javascripts/channels/avatars.coffee
app/assets/javascripts/channels/theatre.coffee

Each service response is now recorded in the client side App object and thus, the stage can be completely redrawn from this state.

Issue #186

---

app/assets/javascripts/cable.js
app/assets/javascripts/channels/avatars.coffee
app/assets/javascripts/channels/dialog.coffee
app/assets/javascripts/channels/theatre.coffee
app/channels/dialog_channel.rb

Issue #189

---

app/assets/javascripts/channels/avatars.coffee

When a player drops the avatar they are holding, the avatar shold be removed from the stage

Drop and Remove Avatar

---

app/views/theatre/foyer.html.erb

This new breakpoint looks like the sm breakpoint but links to the performance space

Add Breakpoint for *-md

---

config/database.yml

Change the test database to behave more like production

Test Database Config

---

app/assets/stylesheets/application.scss

This rule doesn't seem to apply to anything besides the things it shouldn't

Fix table background

---

Gemfile
config/cable.yml

* Redis is now used for test and production
* sqlite3 is only used in development

Fix Config

---

app/assets/stylesheets/application.scss

* Panel titles are now white
* Panel title links are now black on hover

Issue #220: Change Panel Title Styling

---

app/controllers/avatars_controller.rb
app/controllers/backdrops_controller.rb
app/controllers/sounds_controller.rb

When an avatar is deleted:
When a sound is deleted:
When a backdrop is deleted:

When a media item is deleted, it is redirected to media page

---

app/views/announcements/show.html.erb
app/views/avatars/edit.html.erb
app/views/avatars/index.html.erb
app/views/backdrops/edit.html.erb
app/views/backdrops/index.html.erb
app/views/media/_panel.html.erb
app/views/media/_table.html.erb
app/views/sounds/edit.html.erb
app/views/sounds/index.html.erb

**Used class name for deletion message for media items:**
Avatar
Sound
Backdrop
**Used hard code words for deletion message for each item edit page:**
Avatar
Sound
Backdrop

Modified pop-up delete message

---

app/views/theatre/foyer.html.erb
db/seeds.rb

- Audience won't see the accessibility column
- Logged in users:
+ An owner of the stage will see owner.
+ Other logged in users will see player.

Issue#240 Foyer Accessibility

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/media.scss
app/views/announcements/show.html.erb
app/views/avatars/edit.html.erb
app/views/avatars/index.html.erb
app/views/backdrops/edit.html.erb
app/views/backdrops/index.html.erb
app/views/media/_panel.html.erb
app/views/media/_table.html.erb
app/views/media/index.html.erb
app/views/roles/index.html.erb
app/views/roles/show.html.erb
app/views/sounds/edit.html.erb
app/views/sounds/index.html.erb
app/views/stages/_avatars.html.erb
app/views/stages/_backdrops.html.erb
app/views/stages/_sounds.html.erb
app/views/stages/index.html.erb
app/views/stages/show.html.erb
app/views/tags/index.html.erb
app/views/tags/show.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb
config/environments/test.rb
spec/controllers/backdrops_controller_spec.rb

- Using bootstrap modal for the confirmation message
- Should prevent 'Prevent this page from creating additional dialogs' message from appearing on the dialog.

Issue#254 Delete confirmation message

---

app/assets/javascripts/channels/avatars.coffee
app/assets/javascripts/theatre.coffee
app/assets/stylesheets/theatre.scss
app/views/theatre/performance.html.erb

Rearranged the layout of the avatar tool pellet 
added slider for the avatars

Issue#206 Rearranged layout and added avatar slider

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/media.scss
app/views/announcements/show.html.erb
app/views/avatars/edit.html.erb
app/views/avatars/index.html.erb
app/views/backdrops/edit.html.erb
app/views/backdrops/index.html.erb
app/views/media/_panel.html.erb
app/views/media/_table.html.erb
app/views/roles/index.html.erb
app/views/roles/show.html.erb
app/views/sounds/edit.html.erb
app/views/sounds/index.html.erb
app/views/stages/_avatars.html.erb
app/views/stages/_backdrops.html.erb
app/views/stages/_sounds.html.erb
app/views/stages/index.html.erb
app/views/stages/show.html.erb
app/views/tags/index.html.erb
app/views/tags/show.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

The delete message will be shown as following:
- Deleting an avatar from media page
- Deleting a backdrop from media page
- Deleting a stage from stages page
- Unassigning an avatar from a stage

Issue#254 Delete Message

---

app/assets/javascripts/cable.js
app/assets/javascripts/channels/avatars.coffee
app/assets/stylesheets/theatre.scss
app/channels/avatar_channel.rb
app/views/theatre/performance.html.erb

Avatars are able to change name

Issue #205

---

app/assets/javascripts/channels/avatars.coffee
app/views/theatre/performance.html.erb

The diff is a bit wonky - But essentially I've wrapped line 112 -> 123 in an if statement that first checks if the toolbox is available and then only attempts to attach listeners if the tools are there.

Issue #290

---

Gemfile.lock

Patched Nokogiri gem and its dependencies to address vulnerability.

CVE-2017-9050

---

Gemfile
Gemfile.lock

CVE-2017-0889

---

app/assets/javascripts/cable.js
app/assets/javascripts/channels/avatars.coffee

+ Fixed distortion in avatar:
+ Removed duplicated code in avatars.coffee

Issue#275 PR avatar distortion

---

app/assets/javascripts/channels/avatars.coffee

- **The avatar that has just been placed to the canvas will show both name and image to players and audience without placing it again.**
Player View
Audience View
Player View
Audience View
- **The audience will have the avatar removed from their screen when a player drops the avatar.**
Player view
Audience view
Player view
Audience view

Issue #273

---

Gemfile.lock

According to https://github.com/rails/rails/issues/31517 updating the nio4r gem is the solution.  It appears to work.

Issue #315

---

app/views/theatre/performance.html.erb

The Avatar tab is now the default tab when entering a stage and other tabs have been arranged in alphabetical order.

Issue #323

---

.travis.yml

As described here: https://github.com/travis-ci/travis-ci/issues/8969
See: https://github.com/rubygems/rubygems/issues/2123

Address Travis build issue

---

.travis.yml

Backport Emergency Travis fix
